### ISSUE TITLE
Wiki的Donations页面

### ISSUE THREAD

**Issue by easyworld** [majia67/3DS-ARM9LoaderHax-Guide#1]
# Main

Donations页面并不是恶意修改，请看[原wiki的history](https://github.com/Plailect/Guide/wiki/Donations/_history)的[e57fc0a](https://github.com/Plailect/Guide/wiki/Donations/e57fc0adde371b0bb67f7796a3086f6d32933b8c)和[c6def81](https://github.com/Plailect/Guide/wiki/Donations/c6def81c100f9922783eea1db24943c6c8d730ef)。在当时的时间节点，1Ju开头的Bitcoin为最新。
# PS
- 我计划翻译[Region-Changing](https://github.com/majia67/3DS-ARM9LoaderHax-Guide/wiki/Region-Changing)章节，请教如何开展，因为并没有发现您的邮箱地址。

**Comment by majia67** [comment]
抱歉是我的疏忽。我会将你加入合作者列表，这样你就会获得修改wiki的权限。

**Comment by majia67** [comment]
已经发出了邀请。我会在首页标注这部分由你负责，以便防止他人重复劳动。另外我已经更新了我的profile，你可以找到我的邮箱
