### ISSUE TITLE
翻译小问题

### ISSUE THREAD

**Issue by jixunmoe** [majia67/3DS-ARM9LoaderHax-Guide#10]
http://3dshax.cn/decrypt9-(homebrew-launcher)

* 闪存卡带 其实指的是烧录卡

---

http://3dshax.cn/2.1.0-ctrtransfer

If you downgrade to 2.1.0 on a 2DS or New 3DS and left Wireless Communication off, you can re-enable the wireless by removing the battery for several seconds then booting back up.

如果你在 2DS 或 新3DS 降级到 2.1.0 的时候忘了启用无线通信功能的话，你可以按照将电池取出来、等待数秒、然后再插回主机启动的步骤来重新启用无线通信功能。

---

感觉翻译有的地方比较生硬 xD

**Comment by easyworld** [comment]
[Updating-A9LH](https://github.com/majia67/3DS-ARM9LoaderHax-Guide/blob/master/_pages/Updating-A9LH.md) 23行，秘钥->密钥

**Comment by majia67** [comment]
@JixunMoe 感谢你的建议，已采纳你的建议做了调整。
@easyworld 已经同意了你的merge request，多谢建议！
