### ISSUE TITLE
社区在讨论翻译事宜

### ISSUE THREAD

**Issue by wong2** [majia67/3DS-ARM9LoaderHax-Guide#14]
https://github.com/Plailect/Guide/issues/848
https://www.reddit.com/r/3dshacks/comments/5mfn2v/translating_plailects_guide_and_keeping_it/

看起来有可能会放到翻译协作平台上进行

**Comment by jixunmoe** [comment]
https://github.com/Plailect/Guide/commit/49ee6c019a9400c1cc60b5585a019629e96c4dff

看来要换到 crowdin 协作平台了

**Comment by majia67** [comment]
我看了一下讨论帖，迁移过程看来还需要一些时间。协作平台应该是个不错的想法！虽然我现在是计划个人支持这个教程的中文翻译工作的（这样稳定性和翻译语言的一致性会更有保障）。如果最终Plailect决定将教程迁移到Crowdin，我也会将教程迁移过去。但是目前还是等那边稳定之后再考虑。

**Comment by jixunmoe** [comment]
Plailect 已经在 Crowdin 上已经开项目了。

**Comment by majia67** [comment]
已经看到了。等Plailect的正式通知吧。他还在调markdown的格式。等那边setup完之后，我会直接把翻译后的文字贴过去，应该不是很大的工作量。

**Comment by majia67** [comment]
已经确认可以搬过去了，格式保持不变。我这两天做一下迁移。
