### ISSUE TITLE
翻译问题集中汇报帖

### ISSUE THREAD

**Issue by majia67** [majia67/3DS-ARM9LoaderHax-Guide#15]
请将翻译错误和润色建议集中发在这个帖子里，便于统一处理。

**Comment by icekylinH** [comment]
新的那个教程好像用不到D9了 后面在安装A9的时候好像步骤也不同 要不要修改下

**Comment by majia67** [comment]
@icekylinH 多谢提醒！我尽快更新一下

**Comment by icekylinH** [comment]
.....翻译有一个错误..实际上有一步是我看英文原版是复制SafeCTRTransfer.bin并重命名 你这里翻译成了复制SafeCTRTransfer.dat...用dat后面会一直黑屏无法进行下一步..

**Comment by majia67** [comment]
@icekylinH 多谢提醒，已修正

**Comment by lim1202** [comment]
[迁移EmuNAND数据](https://3dshax.cn/move-emunand) 的内容跟 [英文版](https://3ds.guide/move-emunand) 的不大一样，是英文版的版本更新过了吗？

昨天安装A9LH照着中文版做到这步就卡住了，后来照着英文版搞定了……

**Comment by majia67** [comment]
@lim1202 是英文版更新过了。因为时间有限，我前几天只更新了SafeCTRTransfer相关的页面。这周会把其余的页面跟进

**Comment by majia67** [comment]
@lim1202 已更新

**Comment by k17423** [comment]
https://3dshax.cn/installing-arm9loaderhax
第五部分 - 注入FBI
3.进入SDCARD -> files9

（应该是进入SDCARD -> cias）

**Comment by majia67** [comment]
@k17423 已修正

**Comment by 3096** [comment]
话说回来majia不在crowdin干了原因是什么？

**Comment by majia67** [comment]
@3096 不够自由，另外就是我讨厌页面上放很多广告

**Comment by 3096** [comment]
@majia67 那如果crowdin上面更新的话可以从这里搬吗？ （因为license上写了必须要有你的许可）

**Comment by majia67** [comment]
可以，在credits页面写上是从我这里搬的，附上网址就行了

**Comment by majia67** [comment]
本教程已经存档。欢迎大家到新的repository里面对新的教程提出意见。
https://github.com/majia67/3DS-Boot9StrapHax-Guide
