### ISSUE TITLE
大佬我有问题问你，2ds，教程走完了

### ISSUE THREAD

**Issue by darkck** [majia67/3DS-ARM9LoaderHax-Guide#18]
我是日版2ds 11.2.0-35J
你的教程走完了，现在开机是没有动画直接黑屏进系统的，按住select进luma设置，start进hourglass9，应该破解没问题。
但是fbi装任何的cia都是到100失败，说是Desc：Cert signature or hash checkfailed（106）

**Comment by darkck** [comment]
发现一些游戏可以，fbi里有图标显示的都可以安装，大多数容量都比较小，不过大一些的还没有安装成功的，我还要再试一下

**Comment by easyworld** [comment]
确保fbi为最新版，试试下面两个方法:
* 尝试把不能安装cia文件名缩短一点，比如：1.cia
* 检查SD卡是否损坏

**Comment by majia67** [comment]
你做了health & safety inject了么？可以试试那里面的fbi

**Comment by darkck** [comment]
换了三星sdhc卡搞定了，本来是金士顿sdxc的锅

**Comment by majia67** [comment]
hhh果然还是sd卡的问题
