### ISSUE TITLE
aeskeydb.bin not available to download

### ISSUE THREAD

**Issue by CyHo** [majia67/3DS-ARM9LoaderHax-Guide#2]
aeskeydb.bin is not available already, can you tell me where can i download or you can replace a new one , thanks for your help ~~

**Comment by easyworld** [comment]
yep, [old translation](https://github.com/majia67/3DS-ARM9LoaderHax-Guide/wiki/Part-5-%28arm9loaderhax%29/2e6ae88946a2f1b4c31f7ffae566cdb4488191d8) is based on [3a99b1d](https://github.com/Plailect/Guide/wiki/Part-5-%28arm9loaderhax%29/3a99b1d18c0c354faa0c20a0aada508bf9e7a2d8). You can try these links [aeskeydb.bin](https://plailect.github.io/Guide/aeskeydb.torrent) ([mirror1](https://mega.nz/#!Y5UEyIJb!_FLHUUqjtfLaez8FNEM3tG7NHWrkkwmyj93ZNUeOUxI)) ([mirror2](https://drive.google.com/open?id=0BzPfvjeuhqoDTm5VZW1ZcHZ1NzQ)), and the part 5 will be updated soon. Thank you for your response.

## update:

The Part 5 have been updated. You [access](https://github.com/majia67/3DS-ARM9LoaderHax-Guide/wiki/Part-5-%28arm9loaderhax%29/74c45a68c29b2039d4485f2607af1208c37010a0) directly.
