### ISSUE TITLE
希望能对更多的专业术语关键字做链接的跳转。

### ISSUE THREAD

**Issue by heroboy** [majia67/3DS-ARM9LoaderHax-Guide#20]
例如什么事emuNand，sysNand之类的。希望能点击之后跳到专业的网站来解释它。

**Comment by heroboy** [comment]
更多的，例如：https://3dshax.cn/faq 页面：
```
问： 我如何升级Luma3DS？
答： 使用Luma3DS升级器（Luma3DS Updater）。
```
希望能有链接跳到，安装luma3ds updater的安装页面(https://3dshax.cn/installing-arm9loaderhax)

**Comment by majia67** [comment]
这是一个好建议！现在的教程已经不再需要用到emuNAND，如果是之前做过虚拟系统的玩家应该知道这两者之间的区别。如果有好的链接可以po到这里，我可以加上。

**Comment by heroboy** [comment]
我是新买的已经破解好的3ds。没有经过3ds破解的历史，很多都不了解。虽然网上有很多教程文章，但是由于不了解历史，我也不能很好的分辨哪些是新的哪些是废弃的技术。
我觉得你的网站的技术很新，和我的3ds的破解也是匹配的。想了解一下。

但是我发现很多都是很详细的步骤，但是却没什么解释。例如：很多步骤都会出现，“安装XXX”（XXX是个英文字母的缩写），却完全没有关于XXX的解释，也没有相关的连接跳转。毕竟我只是想来学习一下，而不是只是为了破解一台机器。

**Comment by heroboy** [comment]
我觉得https://github.com/AuroraWright/Luma3DS 上面对自制程序解释很好。
> Luma3DS is a program to patch the system

网站首页上面关于custom firmware的解释只是说了它能干什么。名字会让人觉得`自制系统`是*替换*了任天堂做的这个*操作系统*。

我其实有很多问题想问。能不能在这里问呢？还是只处理翻译的问题？

**Comment by easyworld** [comment]
关于NAND相关的知识可以在[https://www.3dbrew.org/wiki/NAND_Redirection](https://www.3dbrew.org/wiki/NAND_Redirection)看到。 
一些关于3DS软硬件详细说明可以在[https://www.3dbrew.org](https://www.3dbrew.org)找到  
问题可以提在这里吧？@majia67

**Comment by heroboy** [comment]
* 其实我最想问的问题是，对于已经破解好的机器，如果sd卡坏了不得不格式化怎么办？（我买来第一天sd卡就坏了，然后去店里换了一台机器）。在这之前我应该备份哪些内容，之后应该怎么恢复（如果没有备份，相应的核心文件应该下载哪一些的）。当然，我只要求能恢复到能正常安装游戏什么的，不需要备份所有游戏存档，如果要备份系统设置应该备份哪些文件等等等等。。。。
* 有的地方说，破解好的机器没有sd卡是不能启动的，但我发现我的sd卡坏了以后其实是能启动的。当然我没有看是不是处于破解状态，只看到title界面出现了。
* 还有就是，你上面说不需要emuNAND了，这是什么意思呢？这就是没有sd卡也能启动的原因吗？破解用的代码，已经写入了sysNAND了吗？

希望能解答我的问题，我觉得第一个问题还是挺实用的。

**Comment by easyworld** [comment]
* 备份SD卡的Nintendo 3ds文件夹和arm9loaderhax.bin即可。如果有其他破解插件（NTR等等）可全部备份。（前提：arm9loaderhax破解）
* 如果是arm9loaderHax并且已经安装FBI，可以按照[第六部分 - 最终设置](https://3ds.guide/zh_CN/installing-arm9loaderhax)的7-12步操作，把arm9loaderhax.bin复制到NAND里，以后关机，拔SD卡，再开机，按照22-24操作即可无SD卡开机。可能买机器的时候商家或者你自己已经做好了上述工作，所以可以无SD卡开机。
* 新版的教程不需要emuNAND了，emuNAND的目的是隔离真实系统，即使emuNAND升级到一个不可破解的版本，可以通过启动sysNAND（此系统为可破解版本）恢复emuNAND到老版本；老版本的教程使用emuNAND是为了防止破解失败留的后路。不是没有sd卡也能启动的原因。在安装arm9loaderhax这步时已经将程序写入sysNAND中。

**Comment by heroboy** [comment]
@easyworld 谢谢谢谢
* 其实我最不想备份的就是`Nintendo 3ds`目录，这个是最大的，所有游戏都装在里面。可以不备份吗？
* `Decrypt9`目录不需要备份是吗？根据我的理解Decrypt9是一个在破解过程中临时用到的程序，是吗？
* `files9` 是一些备份的东西。反正我的3ds也应该不会需要恢复到未破解状态。也没什么用的。
* `luma`目录不需要备份吗？ luma3ds是安装在哪里的呢？`luma`目录是不是只是一些配置文件呢？
* 之前注入的`fbi`程序，被安装在了哪里？是在`Nintendo 3ds`目录吗？（我比较关心如果没有备份这个目录是不是有哪些必要的东西要重装）。

再说一下我对`emuNAND`的理解。`sysNAND`是3ds内置的存储器，`emuNAND`是存在于sd卡上的，所有访问`sysNAND`可以被映射到`emuNAND`上面。因为sd卡可以被方便的读写，所以`emuNAND`可以很容易的被破解。那你为什么说“即使emuNAND升级到一个不可破解的版本”呢，在sd卡上面的`emuNAND`不是可以很容易的被修改破解的吗？

3ds在启动的时候，首先就是加载“arm9loaderhax.bin”，是因为我们之前的某个破解的步骤修改的某个更底层的代码，让它来载入“arm9loaderhax.bin”呢？还是因为"arm9loaderhax.bin”，被写入了NAND中一个固定的地址，3ds启动的时候就会首先载入这个固定的地址呢？ 前面说的`sysNAND`映射到`emuNAND`的破解代码，是存在哪里的，在哪个步骤被破解的呢？

`luma3ds`是由“arm9loaderhax.bin”载入的吗？是因为`luma3ds`在安装的时候，把自己写入某个类似与`autoexec.bat`这样的文件吗？

对于已经破解好的机器，`luma3ds`、`arm9loaderhax.bin`以及一个类似`fbi`cia安装程序，这3个程序是必要的破解程序？其它看到的一些程序只是破解过程中临时用到的程序？

啊呀，不小心就问了那么多问题了啊。毕竟，如果3ds坏了，要自己修。我比较关心怎么样恢复到一个最简的系统。

顺便问一下，3ds进入之后，看到了“桌面”这个程序叫什么呢？包括内置的“设置” "eshop" "mii" 程序之类的。这些个内置程序，可以装一个美版的吗？日文实在是看不懂。

**Comment by easyworld** [comment]
* 安装的cia app都在`Nintendo 3ds`里面，可以不备份，但是sd卡换了之后，app什么的需要重新安装，像是FBI也要重新安装。假如health&safe(三角感叹号图标的app)没有注入或者注入还原了话需要重新注入fbi才能安装cia。
* `Decrypt9`是个多功能程序，可以对NAND进行读写，进行各种相关的加密解密获取key等等操作。
* `Decrypt9`和`files9`都是`Decrypt9`的工作目录，一个对应老版本一个对应新版本。里面是一些Decrypt9生成的或需要的文件，具体见[https://github.com/d0k3/Decrypt9WIP#support-files](https://github.com/d0k3/Decrypt9WIP#support-files)和[https://github.com/d0k3/Decrypt9WIP#working-folders](https://github.com/d0k3/Decrypt9WIP#working-folders)，Support files里面说的可以保留，其他可以都删掉。
* luma目录可以备份一下，里面的payload目录存放着一些像是Decrypt9工具的执行文件，还有luma的配置文件
* FBI注入到了h&s（黄色感叹号）这个app里，这个app是系统应用，所以，在NAND里（如果是虚拟系统，则在emuNAND）。

sysNAND和emuNAND相当于一个计算机装了两个操作系统，互不干扰。通过一个启动加载器决定启动哪个系统。  

目前对于emuNAND和sysNAND一样都不能方便的降级，如果升级到了无可用漏洞的版本，只能用类似ghost恢复的方法恢复到之前的一个备份上。只是在emuNAND恢复比较安全，假如恢复失败，可以继续恢复，但sysNAND恢复挂了可能就没法启动了。  

3ds启动可以[在这里](https://www.3dbrew.org/wiki/Bootloader)看到具体流程，a9破解在boot9的时候动手脚，让其加载了sd卡上的arm9loaderhax.bin。这里的arm9loaderhax.bin就是一个名字，他可以是一个带画面的启动器或者就是luma3ds。当他是luma3ds时，会根据luma目录下的配置决定启动sys还是emuNAND。

fbi最主要是用来装cia的。luma3ds是用来引导sysNAND还是emuNAND并对启动的系统加修改以支持像是跨区，系统设置显示emu，sys这样功能的程序。

桌面叫HOMEmenu，其他可以装美版，但eshop装不同区域的会无法使用。

**Comment by majia67** [comment]
其实除了存档和NAND dump，其它的东西都不需要备份。

**Comment by heroboy** [comment]
@easyworld 感谢感谢！
@majia67 能详细说一下吗？NAND dump怎么备份，怎么恢复？
备份存档，是直接备份sd卡上的文件；还是用3ds自带的存档备份功能，然后再把文件拷贝出来；还是用第三方的存档工具？

**Comment by majia67** [comment]
NAND dump就是SysNAND的导出文件，在做A9破解的过程中会引导你备份，文件名一般是叫“NANDmin”，并且教程会让你将它备份到多个安全的地方。这是在你系统崩溃的时候最简单的恢复办法。一般系统升级后我都会自行再做一份NAND dump，这样恢复的时候也是到最新版本。

存档既可以使用3DS自带的备份功能，也可以用第三方软件，比如savMenu，JKSM之类
