### ISSUE TITLE
Plailect英文教程已经更新11.3嘞！！！

### ISSUE THREAD

**Issue by tanganjie** [majia67/3DS-ARM9LoaderHax-Guide#21]
麻烦这里尽快更新下吧

![20170413102454](https://cloud.githubusercontent.com/assets/13444694/24987595/6aca1312-2033-11e7-8ac0-4f589daac5f4.jpg)

**Comment by majia67** [comment]
Cool! 会尽快更新的。看了一下主要是把fasthax换成了udsploit

**Comment by majia67** [comment]
@tanganjie 已更新
