### ISSUE TITLE
升級至 boot9strap

### ISSUE THREAD

**Issue by syhily** [majia67/3DS-ARM9LoaderHax-Guide#22]
原教程更新新的升級教程 https://3ds.guide/updating-to-boot9strap

**Comment by majia67** [comment]
最近已经在着手弄新教程了。更新量比较大

**Comment by easyworld** [comment]
可以再开个项目3DS-Boot9StrapHax-Guide，本项目加个updating-to-boot9strap的升级页。

**Comment by majia67** [comment]
好想法，已经准备新开项目了。新的文本已经翻译了90%，明后天应该能发布

**Comment by majia67** [comment]
已经发布了。DSiWare的两个注入教程还没有翻译。另外这两天原作者有更新，还没跟进。这两天会继续补上。

**Comment by syhily** [comment]
Tks for your hard work.
