### ISSUE TITLE
Godmode9.bin 问题

### ISSUE THREAD

**Issue by todouu** [majia67/3DS-ARM9LoaderHax-Guide#23]
问题出现在收尾工作页面里面:
第一步12项 你说要把 `GodMode9.bin` 文件复制到 `/luma/payloads/` 目录下. 
然后第四部分的开始 需要按start进入 Luma3DS启动器菜单

我不知道我是不是哪里出问题了,之前的步骤我是严格执行的.
可是不论如何我按start都无法进入 Luma3DS启动器菜单.
然后我去官方的[wiki <-这里是链接](https://github.com/AuroraWright/Luma3DS/wiki/Other-features-and-notes)  payloads chainloading部分上看. 他好像需要 `*.firm` 放入 payloads目录下.
我尝试了吧 `GodMode9.firm` 放入payloads目录下, 然后start键就可以工作了.

谢谢你的翻译

**Comment by majia67** [comment]
多谢提醒，已经修复
