### ISSUE TITLE
 用浏览器安装 arm9loaderhax 时花屏后直接用电源键关机， 然后不能开机了（只会闪一下蓝灯）

### ISSUE THREAD

**Issue by free360x** [majia67/3DS-ARM9LoaderHax-Guide#24]
输完网址以后下屏出现花屏， 我按了一下select以后没有反应， 我就直接按电源键强制关机了。现在开机的时候只会闪一下蓝灯，屏幕不会亮。

我这个是不是变砖了，请问还有补救的办法吗

谢谢！

**Comment by easyworld** [comment]
/a9lh/目录下有文件了吗

**Comment by free360x** [comment]
有了， 有data_input.zip和arm9loaderhax.7z解压出来的文件

**Comment by free360x** [comment]
我问题解决了，我没有按住select开机。。。。。。
多谢回复
