### ISSUE TITLE
安装完“第三部分 - 安装boot9strap”后机器启动不了。

### ISSUE THREAD

**Issue by heximing** [majia67/3DS-ARM9LoaderHax-Guide#26]
按电源键开机，电源灯（蓝色）亮了1秒，然后就暗了，启动不了。
我完全按照教程来的。唯一可能没按教程的是新手包不是最新版本，因为之前我都用Ninjhax 进Homebrew 玩日版游戏。我的Ninjhax 是2.8，而不是最新的2.9。
我的机器是美版，系统版本 10.2.0.35U。
拆开机器拿出SD 卡。里面没有任何.log 文件。

**Comment by heximing** [comment]
我发现一个问题。在https://3dshax.cn/installing-boot9strap-(homebrew-launcher) 第一步，文字是说复制boot.firm，但附图是boot.3ds。可能是因为这个，我复制了错误的文件。还有救吗?

**Comment by heximing** [comment]
我发现我是没复制boot.firm。那个boot.3dsx 是之前用ninjhax 的时候就复制了的。所以我就是少了一个文件。现在开不了机了。

**Comment by heximing** [comment]
SD卡里boot9strap文件夹里多了一个firm0firm1.bak 文件。其它没有了，没有任何.log 文件


我想把这文件上传上来，但提示：
We don’t support that file type.  Choose Files Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP.

我已经打包成zip 了啊！

**Comment by easyworld** [comment]
是在[installing-boot9strap](https://3dshax.cn/installing-boot9strap-(homebrew-launcher))第三部分操作完成后出现了这样的情况吗？

如果是，把luma3ds的boot.firm复制进去sd卡根目录试试呢。

**Comment by heximing** [comment]
boot.firm 复制进去，但还是开不了机。我把SD 卡拔了都开不了机。把SD卡插进去也是开不了机。

**Comment by majia67** [comment]
感谢反馈，图片错误已经修复。

请确保已经成功安装boot9strap。没有放boot.firm文件不会影响b9s的安装。

请尝试按照[这个链接](https://3dshax.cn/troubleshooting#ts_sys_b9s)操作，看能不能修复。

**Comment by heximing** [comment]
我试过楼上的链接里的方法还是启动不了。我不肯定是否成功安装B9S，因为现在机器是完全点不亮，启动不了。最后我只能寄给Nintendo 保修了，过了1年质保他们要价$100 最后砍成$63。

我拿了朋友的其它3台机器测试，系统分别是：11.1, 11.3, 11.4。都很顺利。直接按教程一步步做很快就成功了，所以变砖那台我几乎肯定是复制少了boot.firm 文件导致的。

另外在“收尾步骤”里中文版本的方法对于11.4 的机器会出错的，这个我在“翻译问题集中汇报帖”已经反馈过了。这里我再复制粘贴一下：

> 收尾工作那里。英文版是下载新的hbl(2.0 版本) 覆盖原有的(1.11 版本)。这个对11.4 的机器很重要，因为现在中文版的方法是注入FBI，这个在11.4 的机器上是报错的注入不了的。英文版的方法是先进HOMEBREW 再运行fbi.3dsx。因为我的是11.4 的机器，所以我发现了这个问题。

这篇贴子其实可以关闭掉了，因为问题机器已经拿去修了。 谢谢你们的无私奉献。

**Comment by majia67** [comment]
真抱歉，可能是一个未知的bug。其实我在想有没有可能是SD卡的问题。感谢你的支持，希望你早点拿到修好的机器~
