### ISSUE TITLE
从A9LH升级到B9S，第四部分笔误

### ISSUE THREAD

**Issue by dahuang0210** [majia67/3DS-ARM9LoaderHax-Guide#27]
第6小步，翻译部分写的是选择”ctrtransfer_ticket_copy”，但实际并无此文件，查看3ds.guide后发现，此处应为setup_ctrnand_luma3ds。
望修改！

**Comment by majia67** [comment]
已修正。多谢提醒！

From: dahuang0210
Sent: Tuesday, August 15, 2017 6:52 PM
To: majia67/3DS-ARM9LoaderHax-Guide
Cc: Subscribed
Subject: [majia67/3DS-ARM9LoaderHax-Guide] 从A9LH升级到B9S，第四部分笔误 (#27)

第6小步，翻译部分写的是选择”ctrtransfer_ticket_copy”，但实际并无此文件，查看3ds.guide后发现，此处应为setup_ctrnand_luma3ds。
望修改！
