### ISSUE TITLE
Cannot open the EmuNAND9

### ISSUE THREAD

**Issue by CyHo** [majia67/3DS-ARM9LoaderHax-Guide#3]
Thanks for the previous issue, now i cannot open the EmuNAND9 while i press Y. I did change the name of EmuNAND9 to y_EmuNAND9, can you please help?

**Comment by easyworld** [comment]
Follow the guide we post, or just read the [original one](https://github.com/Plailect/Guide/wiki). It contains all instructions you need. Are you omit something? Which step are you in?

btw, rename may works. :smirk:

**Comment by CyHo** [comment]
i follow all the instruction given but i can't boots to emunand, Hourglass9, or other while i press the button accordingly, Everytime i press, it will move to home menu directly....i won't come out with the emunand, Hourglass9, HBL

**Comment by easyworld** [comment]
Hold Y and press power-on simultaneously, or hold Y before you press power-on button~

**Comment by majia67** [comment]
The button detection is very fast during the booting stage. Do as easyworld said and see if the problem solved.
