### ISSUE TITLE
The version 10.7 can be follow the guilde as shown already?

### ISSUE THREAD

**Issue by CyHo** [majia67/3DS-ARM9LoaderHax-Guide#4]
as refer to the guide of plailect, version 10.7 can be mod with follow the same guide as here already? Need to make sure because want to mod a 10.7 New 3ds XL

**Comment by majia67** [comment]
Don't use the guide here. I haven't updated the guide for a while due to some personal reasons and the guide is obsolete. Use plai's guide and I will update soon.

**Comment by majia67** [comment]
Sorry for the mistake. This guide uses RedNAND and is more complicated than the new guide, but it should work. You may reference this guide, but I still suggest to use the new guide.
