### ISSUE TITLE
原教程格式已发生很大的调整

### ISSUE THREAD

**Issue by majia67** [majia67/3DS-ARM9LoaderHax-Guide#5]
原作者已经将教程从wiki格式改为网页版，我们是不是也要考虑做相应的调整？

另外，因为没有了history可以参考，之后的教程更新工作会比较麻烦……也许只能考虑定期将原教程网站打包下来，然后比对？这样会给我们的更新协作造成困难。有没有什么好的建议？

**Comment by majia67** [comment]
另外不得不吐槽一下原作者，教程的格式一变再变，其实并不是很必要…只会给翻译工作带来困难。之前和原作者交流，他表示不欢迎翻译，因为翻译的更新总是不够快。我也是很无语……

**Comment by easyworld** [comment]
就跟着他用jekyll吧，history其实也[能看](https://github.com/Plailect/Guide/commits/master)  
要不开个新账号维护这个教程？

**Comment by Jerry-Shaw** [comment]
话说，其实教程内容差不多已经稳定了，现在就是一直是格式在改变，还有就是针对新固件有不定的新的降级破解方法，就是国内很多看不懂英文的坑爹了，虽然我一直看英文的，但是还是支持下翻译工作，有必要，我们也做网页？

**Comment by majia67** [comment]
嗯嗯，改成jekyll可以，他是把wiki给删了然后直接在自己的github website下面host了网页版。我昨天没发现怎么看history，多谢提醒 @easyworld 。

我先把他的网页clone过来，然后咱们把中文贴一下，应该就可以了。另外他加了广告代码，咱们去掉吧。

**Comment by majia67** [comment]
我已经把plai的教程push到这个repo的code里面了。我们讨论一下怎么分工？

**Comment by easyworld** [comment]
先研究研究最佳实践，周末再改吧。

**Comment by wong2** [comment]
感谢各位

**Comment by majia67** [comment]
我已经把repository同步到最新的原版教程。

先说一下这次翻译的原则：
1. 尽量保留之前的翻译内容和翻译风格
2. 去除广告、做种等无关信息

分工初步考虑如下：
1. 我负责教程主体和首页的翻译
2. easyworld负责FAQ、Troubleshooting等其它所有页面的翻译
如果有其它人加入，咱们可以把工作再分配一下。

**Comment by majia67** [comment]
另外这次教程是用jekyll写的，我还不太清楚怎么改比较好，是直接改_pages里面的内容，还是用其它的工具？

广告怎么移除也不是很清楚，请大家多多指教。

**Comment by majia67** [comment]
刚才我研究了一下。安装jekyll需要安装ruby和rubygems，另外需要安装bundler。jekyll和bundler都是通过rubygems安装的。然后bundle install安装所有需要的gems。最后jekyll build就可以本地编译网站了。

广告我看了一下这个教程，估计原作者也是这么弄的。
http://www.lewisgavin.co.uk/Google-Analytics-Adsense/

**Comment by majia67** [comment]
我已经完成了主教程翻译，目前在翻译其余页面。这次新增和改写内容大概占到了30%~40%，变化还是比较大的。已经在原教程的wiki页面发布了公告，建议大家不再使用原教程。

**Comment by majia67** [comment]
经过慎重考虑，我决定以后自己更新和维护这个教程，以确保教程语言和风格的连贯性，以及更新频率。感谢各位合作者之前的帮助，我会在致谢页面一直保留各位的贡献。欢迎在issues中继续跟我沟通教程的问题，以及给我建议。谢谢
