### ISSUE TITLE
关于NFIRM词汇统一翻译的问题

### ISSUE THREAD

**Issue by easyworld** [majia67/3DS-ARM9LoaderHax-Guide#8]
[9.2.0-Downgrade](https://github.com/majia67/3DS-ARM9LoaderHax-Guide/blob/master/_pages/9.2.0-Downgrade.md) 的23行固件降级是不是应该统一为NFIRM降级会比较好？
---
ps:favicon很赞:)，域名很赞，可以用cloudflare搞成https的玩~

**Comment by majia67** [comment]
多谢！我改一下。
plai最近更新很勤啊，又调了格式，本来以为这波可以暂告一段落了2333

**Comment by easyworld** [comment]
是啊，现在11.2的也可以降级了

**Comment by majia67** [comment]
9.2.0 Downgrade页面在最新的commit中已经删除了。看来降级已经全面转为ctrtransfer的形式了（连NFIRM Downgrade的链接都暂时不在主教程中）

**Comment by easyworld** [comment]
[installing-arm9loaderhax](https://github.com/majia67/3DS-ARM9LoaderHax-Guide/blob/master/_pages/Installing-arm9loaderhax.md)页面的234行"升级arm9loaderhax"需要与264行“升级A9LH”统一

**Comment by majia67** [comment]
多谢。我这两天抽时间把教程再读一遍，把不一致的地方改一下，同时润色一下语言

**Comment by majia67** [comment]
如果有看到不一致的地方请继续发在这里

**Comment by majia67** [comment]
已经全站启用了https

**Comment by majia67** [comment]
反馈的翻译问题都已经更正。

**Comment by easyworld** [comment]
<del>chrome55 报网页不安全!<del>
  
已经正常
